### ISSUE TITLE
Need help with installation.

### ISSUE THREAD

**Issue by CantBeKarma** [FiveM-Scripts/libgui#6]
I can't actually seem to get this library to work within my own resource for some reason. I've attempted installation like your typical libraries out there (such as: https://github.com/FiveM-Scripts/NativeUILua and https://github.com/iTexZoz/NativeUILua_Reloaded/wiki/NativeUI.WhoToUse.CrossRessourceFile) but to no avail. 

It'd be neat if there were some proper documentation with step by step on how to actually get this working on your existing resource with an **example/explanation** (I'm aware there's a **cl_test.lua** with an example but there isn't actually any explanation to go along with that). All I personally want to know though is how to actually install this lib however. Thanks.

**Comment by pongo1231** [comment]
Installation is like any other resource: just drag and drop the folder inside your resources folder and add it to your server.cfg.

There are two caveats however (and you are right, these should be mentioned in the README): you have to make sure the resource is named "libgui" (it's hardcoded on the NUI side) and the resource has to be started **after** all the other resources that depend on it (as it triggers an event once it initializes to pass an interface builder).

Hope that clarifies it up. I'll add the setup instructions to the docs asap. Thanks for mentioning it.

**Comment by CantBeKarma** [comment]
> 
> 
> Installation is like any other resource: just drag and drop the folder inside your resources folder and add it to your server.cfg.
> 
> There are two caveats however (and you are right, these should be mentioned in the README): you have to make sure the resource is named "libgui" (it's hardcoded on the NUI side) and the resource has to be started **after** all the other resources that depend on it (as it triggers an event once it initializes to pass an interface builder).
> 
> Hope that clarifies it up. I'll add the setup instructions to the docs asap. Thanks for mentioning it.

Yup, reading your response made me look back on my resources.cfg and realize that I was starting "libgui" prior to my resource. It's now working, thanks for the quick response and the information. You should definitely add those setup instructions to avoid frustration in the future to whomever stumbles across this lib, yeah. I'll leave this issue open as a **reminder** to add setup instructions to the doc.
